name: This is a test workflow

on:
  push

jobs:
  my_job:
    runs-on: ubuntu-latest
    
    steps:
      - name: firsty
        run: |
          echo firsty
          echo is thirsty

  new_job:
    needs: my_job
    runs-on: ubuntu-latest

    steps:
      - name: secundi
        run: |
          echo $GITHUB_SHA
        
