name: This is a test workflow

on:
  push

jobs:
  my_job:
    runs-on: ubuntu-latest
    
    steps:
      - name: firsty
        run: |
          echo firsty
          echo is thirsty

  new_job:
    runs-on: ubuntu-latest

    steps:
      - name: set-envy
        run: |
          echo "ENVY_1=this env is set in secundi" >> $GITHUB_ENV
      - name: secundi
        run: |
          echo $GITHUB_SHA

  trenta:
    runs-on: ubuntu-latest
    needs: new_job

    steps:
      - name: printy
        run: |
          echot $ENVY_1

      
