name: This is a test workflow

on:
  push

jobs:
  my_job:
    runs-on: ubuntu-latest
    
    steps:
      - name: firsty
        run: |
          echo firsty
          echo is thirsty

  new_job:
    runs-on: ubuntu-latest
    outputs:
      ENVY_1: ${{ steps.exporty.outputs.ENVY_1 }}
    steps:
      - name: set-envy
        run: echo "ENVY_1=this env is set in secundi" >> $GITHUB_ENV
      - name: secundi
        run: echo $GITHUB_SHA
      - name: exporty
        run: echo "::set-output name=ENVY_1::$(echo $ENVY_1)"

  trenta:
    runs-on: ubuntu-latest
    needs: new_job

    steps:
      - name: printy
        run: |
          echo "The value of my env is: ${{needs.new_job.outputs.ENVY_1}}"
