name: This is a test workflow

on:
  push

jobs:
  my_job:
    runs-on: ubuntu-latest
    
    steps:
      - name: firsty
        run: |
          echo firsty
          echo is thirsty

  secundi:
    runs-on: ubuntu-latest
    outputs:
      ENVY_1: ${{ steps.exporty.outputs.ENVY_1 }}
    steps:
      - name: exporty
        id: exporty
        run: echo "ENVY_1=this env is set in secundi" >> $GITHUB_OUTPUT

  trenta:
    runs-on: ubuntu-latest
    needs: secundi

    steps:
      - name: printy
        run: |
          echo "The value of my env is: ${{needs.secundi.outputs.ENVY_1}}"
